function [best_path, best_length] = lkhTSP(cost_mat)
    [n, m] = size(cost_mat);
    if n ~= m, error('输入的成本矩阵必须是方阵!'); end
    if any(isnan(cost_mat(:))) || any(isinf(cost_mat(:))), error('成本矩阵中包含 NaN 或 Inf 值。'); end

    problem_name = 'tsp_problem';
    [problem_file, param_file, output_file] = write_LKH_files(cost_mat, problem_name);

    LKH_executable = fullfile(pwd, 'LKH', 'LKH.exe');
    lkh_cmd = sprintf('echo. | "%s" "%s"', LKH_executable, param_file);
    [status, ~] = system(lkh_cmd);
    
    if status ~= 0
        warning('LKH 执行可能失败，请检查 LKH 路径、文件权限以及输出信息。');
        best_path = [];
        best_length = inf;
        return;
    end
    
    if ~exist(output_file, 'file'), error('LKH 未能生成结果文件: %s', output_file); end

    fileID = fopen(output_file, 'r');
    if fileID == -1, error('无法打开结果文件: %s', output_file); end

    line = fgetl(fileID);
    while ischar(line) && ~contains(line, 'TOUR_SECTION'), line = fgetl(fileID); end
    
    best_path = fscanf(fileID, '%d');
    fclose(fileID);
    
    best_path = best_path(best_path ~= -1 & best_path ~= 0)';
    
    if isempty(best_path)
        warning('LKH未能找到有效路径。');
        best_length = inf;
    else
        path_indices = sub2ind(size(cost_mat), best_path, [best_path(2:end), best_path(1)]);
        best_length = sum(cost_mat(path_indices));
    end
end

function [problem_file, param_file, output_file] = write_LKH_files(cost_mat, problem_name)
    LKH_dir = fullfile(pwd, 'LKH');
    TSPLIB_dir = fullfile(LKH_dir, 'TSPLIB');
    if ~exist(TSPLIB_dir, 'dir'), mkdir(TSPLIB_dir); end

    problem_file = fullfile(TSPLIB_dir, [problem_name, '.tsp']);
    param_file   = fullfile(TSPLIB_dir, [problem_name, '.par']);
    output_file  = fullfile(TSPLIB_dir, [problem_name, '.tour']);

    fileID = fopen(problem_file, 'w');
    if fileID == -1, error('无法创建或打开 .tsp 文件进行写入: %s', problem_file); end
    
    fprintf(fileID, 'NAME: %s\n', problem_name);
    fprintf(fileID, 'TYPE: TSP\n');
    fprintf(fileID, 'COMMENT: Symmetric TSP generated by MATLAB\n');
    fprintf(fileID, 'DIMENSION: %d\n', size(cost_mat, 1));
    fprintf(fileID, 'EDGE_WEIGHT_TYPE: EXPLICIT\n');
    fprintf(fileID, 'EDGE_WEIGHT_FORMAT: FULL_MATRIX\n');
    fprintf(fileID, 'EDGE_WEIGHT_SECTION\n');
    
    cost_mat_int = round(cost_mat);
    for i = 1:size(cost_mat_int, 1)
        fprintf(fileID, ' %d', cost_mat_int(i, :));
        fprintf(fileID, '\n');
    end
    
    fprintf(fileID, 'EOF\n');
    fclose(fileID);

    fileID = fopen(param_file, 'w');
    if fileID == -1, error('无法创建或打开 .par 文件进行写入: %s', param_file); end
    
    fprintf(fileID, 'PROBLEM_FILE = %s\n', problem_file);
    fprintf(fileID, 'MOVE_TYPE = 5\n');
    fprintf(fileID, 'PATCHING_C = 3\n');
    fprintf(fileID, 'PATCHING_A = 2\n');
    fprintf(fileID, 'RUNS = 10\n');
    fprintf(fileID, 'TOUR_FILE = %s\n', output_file);
    fclose(fileID);
end
